import { describe, expect, it } from "vitest";
import { notificationSchema } from "@notifications/shared";
import { buildCustom, generateBurst, generatePreset, PRESET_IDS } from "./generate";
import { lookupModule } from "./modules/registry";

const MODULE_KEYS = ["dsr", "access-governance", "data-mapping", "assessments"];

function expectActionable(notification: ReturnType<typeof buildCustom>): void {
  const parsed = notificationSchema.safeParse(notification);
  expect(parsed.success).toBe(true);
  expect(notification.actions?.length ?? 0).toBeGreaterThan(0);
  const mod = lookupModule(notification.module);
  expect(mod).toBeDefined();
  for (const action of notification.actions ?? []) {
    expect(action.kind).toBe("dispatch");
    if (action.kind === "dispatch") {
      const entry = mod?.catalog.find((c) => {
        const made = c.makeAction();
        return made.kind === "dispatch" && made.path === action.path;
      });
      expect(entry).toBeDefined();
      expect(entry?.method).toBe(action.method);
    }
  }
}

describe("generateBurst", () => {
  it("produces `count` valid, actionable notifications across the four modules", () => {
    const batch = generateBurst(12, 42);
    expect(batch).toHaveLength(12);
    for (const n of batch) {
      expect(MODULE_KEYS).toContain(n.module);
      expectActionable(n);
    }
  });

  it("is deterministic given the same seed for the generator-controlled fields", () => {
    // Action *metadata* (e.g. a catalog entry's requestId) is generated by the module's own
    // makeAction() via Math.random(), independent of generate.ts's seeded rng — by design,
    // matching how a real module would mint its own state. Only the fields generate.ts itself
    // derives from the seed (module/template selection, ids, descriptions, audience) are
    // expected to reproduce exactly.
    const a = generateBurst(5, 7);
    const b = generateBurst(5, 7);
    const strip = (batch: ReturnType<typeof generateBurst>) =>
      batch.map(({ actions, ...rest }) => rest);
    expect(strip(a)).toEqual(strip(b));
    expect(a.map((n) => n.id)).toEqual(b.map((n) => n.id));
  });

  it("produces unique ids within a burst", () => {
    const batch = generateBurst(30, 99);
    const ids = new Set(batch.map((n) => n.id));
    expect(ids.size).toBe(batch.length);
  });
});

describe("generatePreset", () => {
  it.each(PRESET_IDS)("produces a valid, actionable batch for preset %s", (id) => {
    const batch = generatePreset(id);
    expect(batch.length).toBeGreaterThan(0);
    for (const n of batch) expectActionable(n);
  });
});

describe("buildCustom", () => {
  it("builds one valid, actionable notification from provided fields + catalog action names", () => {
    const n = buildCustom({
      module: "dsr",
      title: "Custom DSR alert",
      description: "A hand-authored scenario for QA.",
      priority: "high",
      actions: ["approve"],
    });
    expectActionable(n);
    expect(n.title).toBe("Custom DSR alert");
    expect(n.priority).toBe("high");
  });

  it("throws for an action name not in the module's catalog", () => {
    expect(() =>
      buildCustom({
        module: "dsr",
        title: "Bad",
        description: "Bad",
        priority: "low",
        actions: ["not-a-real-action"],
      }),
    ).toThrow();
  });

  it("throws for an unknown module", () => {
    expect(() =>
      buildCustom({
        module: "not-a-module",
        title: "Bad",
        description: "Bad",
        priority: "low",
        actions: ["approve"],
      }),
    ).toThrow();
  });

  // Regression: a plain `modules[key]` property lookup would resolve inherited
  // Object.prototype keys ("__proto__", "constructor", "toString") as truthy hits instead of
  // 404ing/erroring as unknown modules. `module` here is untrusted `/emit` request input.
  it.each(["__proto__", "constructor", "toString"])(
    "throws for the prototype-chain key %s instead of treating it as a known module",
    (moduleKey) => {
      expect(() =>
        buildCustom({
          module: moduleKey,
          title: "Bad",
          description: "Bad",
          priority: "low",
          actions: ["approve"],
        }),
      ).toThrow(`unknown module: "${moduleKey}"`);
    },
  );
});
