#!/usr/bin/env python3
"""Generate a self-contained interactive HTML Gantt chart from a JSON task list.

Usage: python3 generate_gantt.py tasks.json output.html
"""
import json
import sys
from html import escape

ROW_H = 40
LEFT_W = 260
DAY_W = 28
TOP_PAD = 60
PALETTE = ["#3b6ea5", "#4d8b6f", "#a56a3b", "#7d5ba6", "#b0523f", "#3b8a8c", "#8a7a3b"]


def load_tasks(path):
    with open(path) as f:
        tasks = json.load(f)
    for t in tasks:
        t.setdefault("dependsOn", [])
    return tasks


def build_svg(tasks):
    max_day = max((t["start"] + t["duration"] for t in tasks), default=10)
    width = LEFT_W + max_day * DAY_W + 40
    height = TOP_PAD + len(tasks) * ROW_H + 20
    id_to_row = {t["id"]: i for i, t in enumerate(tasks)}

    parts = [f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" font-family="ui-sans-serif, system-ui, sans-serif">']

    # day gridlines + labels (every 5 days)
    for d in range(0, max_day + 1, 5):
        x = LEFT_W + d * DAY_W
        parts.append(f'<line x1="{x}" y1="{TOP_PAD - 20}" x2="{x}" y2="{height - 10}" stroke="#e5e7eb" stroke-width="1"/>')
        parts.append(f'<text x="{x}" y="{TOP_PAD - 28}" font-size="11" fill="#6b7280" text-anchor="middle">day {d}</text>')

    parts.append(f'<line x1="{LEFT_W}" y1="{TOP_PAD - 20}" x2="{LEFT_W}" y2="{height - 10}" stroke="#9ca3af" stroke-width="1.5"/>')

    for i, t in enumerate(tasks):
        y = TOP_PAD + i * ROW_H
        color = PALETTE[i % len(PALETTE)]
        bar_x = LEFT_W + t["start"] * DAY_W
        bar_w = max(t["duration"] * DAY_W, 6)

        # dependency connectors (simple elbow lines)
        for dep_id in t.get("dependsOn", []):
            if dep_id not in id_to_row:
                continue
            dep = tasks[id_to_row[dep_id]]
            dep_end_x = LEFT_W + (dep["start"] + dep["duration"]) * DAY_W
            dep_y = TOP_PAD + id_to_row[dep_id] * ROW_H + ROW_H / 2
            mid_y = y + ROW_H / 2
            parts.append(
                f'<path d="M {dep_end_x} {dep_y} L {dep_end_x + 6} {dep_y} L {dep_end_x + 6} {mid_y} L {bar_x} {mid_y}" '
                f'fill="none" stroke="#c4c9d1" stroke-width="1.5" stroke-dasharray="3,2"/>'
            )

        # row label
        parts.append(f'<text x="8" y="{y + ROW_H / 2 + 4}" font-size="13" fill="#1f2937">{escape(t["name"])}</text>')

        # bar with hover tooltip via <title>
        parts.append(
            f'<g>'
            f'<rect x="{bar_x}" y="{y + 8}" width="{bar_w}" height="{ROW_H - 16}" rx="4" fill="{color}" opacity="0.9">'
            f'<title>{escape(t["name"])} — day {t["start"]} to {t["start"] + t["duration"]} ({t["duration"]}d)</title>'
            f'</rect>'
            f'<text x="{bar_x + 6}" y="{y + ROW_H / 2 + 4}" font-size="11" fill="#ffffff">{t["duration"]}d</text>'
            f'</g>'
        )

        parts.append(f'<line x1="0" y1="{y + ROW_H}" x2="{width}" y2="{y + ROW_H}" stroke="#f1f2f4" stroke-width="1"/>')

    parts.append('</svg>')
    return "".join(parts), width, height


def generate_html(tasks, output_path):
    svg, width, height = build_svg(tasks)
    total_days = max((t["start"] + t["duration"] for t in tasks), default=0)
    html = f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Project timeline</title>
<style>
  body {{ margin: 0; padding: 24px; background: #fafafa; font-family: ui-sans-serif, system-ui, sans-serif; color: #1f2937; }}
  h1 {{ font-size: 18px; margin: 0 0 4px 0; }}
  .meta {{ color: #6b7280; font-size: 13px; margin-bottom: 20px; }}
  .chart-wrap {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; overflow-x: auto; }}
  svg {{ display: block; min-width: {width}px; }}
</style>
</head>
<body>
  <h1>Project timeline</h1>
  <div class="meta">{len(tasks)} milestones · {total_days} days total · generated by the gantt-chart skill</div>
  <div class="chart-wrap">{svg}</div>
</body>
</html>'''
    with open(output_path, "w") as f:
        f.write(html)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 generate_gantt.py <tasks.json> <output.html>")
        sys.exit(1)
    tasks = load_tasks(sys.argv[1])
    generate_html(tasks, sys.argv[2])
    print(f"Generated {sys.argv[2]}")
